_BASE_: "../Sparse-RCNN-FPN/sparsercnn.res101.300pro.3x.yaml"
MODEL:
  META_ARCHITECTURE: "SparseRCNNCPR"
  WEIGHTS: "checkpoints/coco/sparse_rcnn_r101p300/sparse_rcnn_base_lrv1_all_init/model_reset_surgery.pth"
  SparseRCNN:
    NUM_CLASSES: 80
    DEEP_CONSISTENCY: 0
  BACKBONE:
    BKN_FREEZE: True
    FPN_FREEZE: False
  ROI_HEADS:
    FREEZE_FEAT: False
    FREEZE_INIT: False
  PROJ_HEADS:
    PROJ_COM: False
    POS_TOPK: 10
    NEG_RCNT: 10
  CONTRASTIVE:
    THRE_IOU: 0.8
    NCON_IOU: 0.9
    INITACT: False
DATASETS:
  TRAIN: ('coco_trainval_all_10shot',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.00005
  TUNE_MULTIPLIER: 0.5
  STEPS: (6000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 10
INPUT:
  CROP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 500
  PCB:
    ENABLED: False
    ALPHA: 0.5
  AUG:
    ENABLED: False
# OUTPUT_DIR: "checkpoints/coco/sparse_rcnn_r101p300/debug"
OUTPUT_DIR: "checkpoints/coco/sparse_rcnn_r101p300/debug"